# Available options:
# - host
# - port
# - database
# - password
#
# You may also specify the connection as a URL. If you do so, all other
# configuration options will be ignored:
# - url

default: &default
  host: localhost
  port: 6379

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV.fetch("REDIS_URL") { nil } %>
